# Generated by Django 2.0 on 2018-06-22 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Enter your year', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['prog', 'branch'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=7)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Programme')),
                ('year', models.ManyToManyField(help_text='Select year', to='catalog.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Roll no', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'Present'), ('a', 'Absent')], default='a', help_text='Attendance', max_length=1)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Student')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
