# Generated by Django 2.0 on 2018-06-22 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinstance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='batch',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Present'), ('a', 'Absent')], default='a', help_text='Attendance', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Roll no', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='StudentInstance',
        ),
    ]
